# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hr0vzryGPca5ik87Ocmq1BtbKEqb6w7Z
"""

import math

# Koeffitsientlarni kiritish
a = float(input("a (kvadrat had koeffitsienti) ni kiriting: "))
b = float(input("b (chiziqli had koeffitsienti) ni kiriting: "))
c = float(input("c (erkin had) ni kiriting: "))

# Diskriminantni hisoblash
D = b**2 - 4*a*c

# Tenglama yechimlarini topish
if D > 0:
    x1 = (-b + math.sqrt(D)) / (2*a)
    x2 = (-b - math.sqrt(D)) / (2*a)
    print(f"Tenglama ikki haqiqiy ildizga ega: x1 = {x1}, x2 = {x2}")
elif D == 0:
    x = -b / (2*a)
    print(f"Tenglama bitta haqiqiy ildizga ega: x = {x}")
else:
    print("Tenglama haqiqiy ildizga ega emas.")